config/routes.rb
Rails.application.routes.draw do

  root 'books#index'
  
  resources :books
  resources :students, except: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :name, :author, :synopsis, presence: true

    before_save :capitalize_book_name, :capitalize_book_author, :capitalize_book_synopsis

    def capitalize_book_name
        self.name.capitalize!
    end

    def capitalize_book_author
        self.author.capitalize!
    end

    def capitalize_book_synopsis
        self.synopsis.capitalize!
    end
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: %w[show edit update destroy]

  def show; end

  def index
    @books = Book.all 
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @book.update(book_params)
      redirect_to books_path
    else
      render 'edit'
    end
  end 

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:name, :author, :synopsis)
  end

  def find_book
    @book = Book.find(params[:id])
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

    def show
        @student = Student.find(params[:id])
      end
    
      def index
        @students = Student.all 
      end
    
      def new
        @student = Student.new
      end
    
      def create
        @student = Student.new(student_params)
        @student.save
        redirect_to students_path(@student)
      end
    
      def edit
        @student = Student.find(params[:id])
      end
    
      def update
        @student = Student.find(params[:id])
        @student.update(student_params)
        redirect_to students_path(@student)
      end  
      
      def destroy
        @student = Student.find(params[:id])
        @student.destroy
        redirect_to students_path
      end

      private

      def student_params
        params.require(:student).permit(:student, :address)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/books/_form.html.erb
<div class="form-group container">
<%= form_with(model: @book, local: true) do |f| %>
    <strong><%= f.label :name %></strong>
    <%= f.text_field :name, class: "form-control", id: "exampleInputEmail1" %>
    <strong><%= f.label :author %></strong>
    <%= f.text_field :author, class: "form-control", id: "exampleInputEmail1" %>
    <strong><%= f.label :synopsis %></strong>
    <%= f.text_area :synopsis, class: "form-control", id: "exampleInputEmail1" %>
    <p><center><%= link_to "Go Back", books_path, class: "btn btn-outline-dark" %>
    <%= f.submit class: "btn btn-outline-success" %></center></p>
<% end %> 
</div>

app/views/books/edit.html.erb
<center><h1>Edit Book</h1></center>
<%= render 'form' %>
    

app/views/books/index.html.erb
 <center><h1>Books</h1></center>
   
 
 <table class="table container table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Author</th>
      <th scope="col">Synopsis</th>
      <th scope="col" colspan = "4">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <td><%= book.name %></td>
      <td><%= book.author %></td>
      <td><%= book.synopsis %></td>
      <td><%= link_to "Show", book_path(book), class:"btn btn-outline-success" %></td>
      <td><%= link_to "Edit", edit_book_path(book), class: "btn btn-outline-primary" %></td>
      <td><%= link_to "Delete", book_path(book), method: :delete, class:"btn btn-outline-danger", data: {confirm: "Are you sure?"} %></td>
      
    </tr>
    <% end %>
   </tbody>
   </table>

  <%= link_to "Add New Book", new_book_path(@books), class: "btn btn-dark" %>
   
  
   

app/views/books/new.html.erb
<h1><center>Add New Book</center></h1>
<%= render 'form' %>

app/views/books/show.html.erb
<div class="card text-center">
  <div class="card-header">
 
  </div>
  <div class="card-body">
    <h5 class="card-title"><strong>Name: <%= @book.name %></strong></h5>
    <h5 class="card-title"><strong>Author: <%= @book.author %></strong></h5>
    <p class="card-text"><strong>Synopsis: </strong><i><%= @book.synopsis %></i></p>
    <%= link_to "Go Back", books_path, class: "btn btn-info" %>
    <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %>
    <%= link_to "Delete Book", book_path(@book), method: :delete, class:"btn btn-danger", data: {confirm: "Are you sure?"} %>
  </div>
  <div class="card-footer text-muted">
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">    
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav">
            <a href="/books" class="nav-item nav-link active">Books</a>
            <a href="/students" class="nav-item nav-link">Students</a>

    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Librarian</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>

    <div class = 'container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/students/_form.html.erb
<div class="form-group container">
<%= form_with(model: @student, local: true) do |f| %>
    <strong><%= f.label :student %></strong>
    <%= f.text_field :student, class: "form-control", id: "exampleInputEmail1" %>
    <strong><%= f.label :address %></strong>
    <%= f.text_area :address, class: "form-control", id: "exampleInputEmail1" %>
    <p><center><%= link_to "Go Back", books_path, class: "btn btn-outline-dark" %>
    <%= f.submit class: "btn btn-outline-success" %></center></p>
<% end %> 
</div>

app/views/students/edit.html.erb
<center><h1>Edit Student</h1></center>
<%= render 'form' %>

app/views/students/index.html.erb
<center><h1>Students</h1></center>
   
 
<table class="table container table-bordered">
 <thead>
   <tr>
     <th scope="col">Student</th>
     <th scope="col">Address</th>
     <th scope="col" colspan = "4">Actions</th>
   </tr>
 </thead>
 <tbody>
   <% @students.each do |student| %>
    <tr>
      <td><%= student.student %></td>
      <td><%= student.address %></td>
      <td><%= link_to "Edit", edit_student_path(student), class: "btn btn-outline-primary" %></td>
      <td><%= link_to "Delete", student_path(student), method: :delete, class:"btn btn-outline-danger", data: {confirm: "Are you sure?"} %></td>
    </tr>
   <% end %>
  </tbody>
  </table>

 <%= link_to "Add New Student", new_student_path(@students), class: "btn btn-dark" %>

app/views/students/new.html.erb
<center><h1>Add New Student</h1></center>
<%= render 'form' %>